import sqlite3

conn = sqlite3.connect("store.db")
cur = conn.cursor()
conn.row_factory = sqlite3.Row

cur.execute("""
CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT, price INTEGER, original_price INTEGER,
    stock INTEGER, image TEXT, description TEXT, rating REAL, category TEXT
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS cart(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS orders(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT, phone TEXT, address TEXT, city TEXT, pincode TEXT,
    total INTEGER, status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS order_items(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER, product_name TEXT, product_price INTEGER,
    FOREIGN KEY(order_id) REFERENCES orders(id)
)
""")

cur.execute("""
CREATE TABLE IF NOT EXISTS reviews(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id INTEGER,
    reviewer_name TEXT,
    phone TEXT,
    rating INTEGER,
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(product_id) REFERENCES products(id)
)
""")

products = [
    # STATIONARY (50)
    ("Ball Pen Blue",10,0,100,"ballpen_blue.jpg","Smooth writing ballpoint pen",4.5,"stationary"),
    ("Mechanical Pencil 0.7mm",12,0,100,"mechpencil.jpg","Precision mechanical pencil",4.2,"stationary"),
    ("HB Wood Pencil",5,0,100,"woodpencil.jpg","Standard HB pencil",4.4,"stationary"),
    ("Colored Pencils 12 Pack",25,0,100,"colorpencils.jpg","Artist quality colored pencils",4.3,"stationary"),
    ("Spiral Notebook 200pg",40,0,100,"spiralnotebook.jpg","Spiral-bound notebook",4.6,"stationary"),
    ("Permanent Marker Pack",30,0,100,"markers.jpg","Waterproof permanent marker",4.1,"stationary"),
    ("Text Highlighters 5pc",35,0,100,"highlighters.jpg","Fluorescent highlighter set",4.2,"stationary"),
    ("Rubber Eraser Natural",5,0,100,"eraser.jpg","Soft natural rubber eraser",4.0,"stationary"),
    ("Pencil Sharpener Electric",7,0,100,"electricsharpener.jpg","Battery-powered sharpener",4.2,"stationary"),
    ("Grid Notebook A5",100,0,100,"gridnotebook.jpg","Grid pattern notebook",4.5,"stationary"),
    ("Sketch Pad 30 Sheets",60,0,100,"sketchpad.jpg","120gsm sketching paper",4.2,"stationary"),
    ("Complete Geometry Set",120,0,100,"geometryset.jpg","Full compass and scale kit",4.3,"stationary"),
    ("No-slip Stapler",25,0,100,"stapler.jpg","Anti-slip base stapler",4.1,"stationary"),
    ("Transparent Tape Roll",15,0,100,"taperoll.jpg","Clear packing tape",4.0,"stationary"),
    ("PVA Glue Stick Pack",20,0,100,"glue.jpg","Non-toxic glue stick",4.2,"stationary"),
    ("Hardcover Journal",120,0,100,"journal.jpg","Lined hardcover journal",4.4,"stationary"),
    ("Fine Liners 12 Colors",80,0,100,"fineliners.jpg","Precision drawing pens",4.3,"stationary"),
    ("Wax Crayons 24 Pack",50,0,100,"crayons.jpg","Vibrant color crayons",4.2,"stationary"),
    ("Artist Brush Set 10pc",90,0,100,"brushset.jpg","Natural and synthetic brushes",4.1,"stationary"),
    ("Premium Watercolor Set",150,0,100,"watercolors.jpg","24-color wet paint set",4.3,"stationary"),
    ("Copy Paper 500 Sheets",200,0,100,"paper.jpg","A4 white copy paper",4.4,"stationary"),
    ("Memo Pads Neon",60,0,100,"notepads.jpg","Assorted color sticky pads",4.2,"stationary"),
    ("Metal Paper Clips 250pc",30,0,100,"paperclips.jpg","Standard size clips",4.1,"stationary"),
    ("Bamboo Desk Organizer",350,700,25,"deskorganizer.jpg","Natural bamboo construction",4.5,"stationary"),
    ("Monthly Wall Planner",120,0,100,"wallplanner.jpg","12-month planning calendar",4.4,"stationary"),
    ("Dot Grid Bullet Journal",80,0,100,"bulletjournal.jpg","Dot pattern pages",4.2,"stationary"),
    ("Professional Pencil Set",90,0,100,"prosetpencils.jpg","Artist grade pencils",4.3,"stationary"),
    ("Luxury Gel Pen Set",60,0,100,"gelpenset.jpg","Smooth gel ink pens",4.1,"stationary"),
    ("Executive Fountain Pen",100,0,100,"fountainpen.jpg","Premium writing instrument",4.5,"stationary"),
    ("Index Card Box 200pc",45,0,100,"indexcards.jpg","Ruled index cards with box",4.0,"stationary"),
    ("Binder Clips Large 12pc",20,0,100,"binderclips.jpg","Heavy duty binder clips",4.1,"stationary"),
    ("Correction Fluid White",18,0,100,"correctionfluid.jpg","Quick dry correction fluid",4.0,"stationary"),
    ("Ruler 30cm Transparent",12,0,100,"ruler.jpg","Clear acrylic ruler",4.2,"stationary"),
    ("Scissors Stainless Steel",35,0,100,"scissors.jpg","Sharp stainless steel scissors",4.3,"stationary"),
    ("Compass Drawing Set",55,0,100,"compass.jpg","Precision drawing compass",4.2,"stationary"),
    ("A4 Sketch Book 50pg",70,0,100,"a4sketchbook.jpg","White cartridge paper",4.3,"stationary"),
    ("Pen Holder Ceramic",80,0,100,"penholder.jpg","Decorative ceramic pen holder",4.1,"stationary"),
    ("Whiteboard Marker 4pc",40,0,100,"wbmarker.jpg","Dry erase markers set",4.2,"stationary"),
    ("Sticky Notes 5x5 100pc",25,0,100,"stickynotes.jpg","Pastel color sticky notes",4.4,"stationary"),
    ("Calligraphy Pen Set",150,0,100,"calligraphy.jpg","Beginner calligraphy kit",4.3,"stationary"),
    ("Pastel Chalk Set 24pc",65,0,100,"pastelchalk.jpg","Soft pastel chalk colors",4.2,"stationary"),
    ("Sketch Pencil Set 12pc",85,0,100,"sketchpencils.jpg","6B to 2H sketch pencils",4.4,"stationary"),
    ("Acrylic Paint Set 12pc",180,0,100,"acrylicpaint.jpg","Vibrant acrylic colors",4.3,"stationary"),
    ("Canvas Board A4",120,0,100,"canvasboard.jpg","Artist primed canvas board",4.2,"stationary"),
    ("Oil Pastel Set 36pc",95,0,100,"oilpastel.jpg","Smooth oil pastel colors",4.1,"stationary"),
    ("Drawing Board A3",200,0,100,"drawingboard.jpg","Portable drawing board",4.3,"stationary"),
    ("Craft Scissors Decorative",45,0,100,"craftscissors.jpg","Pattern edge scissors",4.0,"stationary"),
    ("Tape Dispenser Desktop",60,0,100,"tapedispenser.jpg","Heavy duty tape dispenser",4.2,"stationary"),
    ("Letter Tray 3 Tier",150,0,100,"lettertray.jpg","Stackable document tray",4.3,"stationary"),
    ("Stamp Pad Ink Blue",30,0,100,"stamppad.jpg","Ink stamp pad blue",4.1,"stationary"),

    # ELECTRONICS (50)
    ("Scientific Calculator",150,0,100,"calculator.jpg","LCD display calculator",4.5,"electronic"),
    ("Wired In-ear Earphones",300,600,25,"earphones.jpg","3.5mm jack earphones",4.4,"electronic"),
    ("USB-C Data Cable 2m",100,0,100,"usbcable.jpg","Fast charging cable",4.3,"electronic"),
    ("Wireless Mouse 2.4GHz",250,0,100,"wirelessmouse.jpg","USB receiver mouse",4.5,"electronic"),
    ("RGB Gaming Keyboard",600,950,25,"gamingkeyboard.jpg","Mechanical switches keyboard",4.6,"electronic"),
    ("LED Desk Lamp USB",450,900,25,"desklamp.jpg","Adjustable color temperature",4.5,"electronic"),
    ("Over-ear Bluetooth Headphones",1200,1900,25,"btheadphones.jpg","Wireless noise-cancelling",4.6,"electronic"),
    ("Fitness Tracker Band",2500,3500,25,"fitnesstracker.jpg","Heart rate and sleep monitor",4.5,"electronic"),
    ("USB Hub 4 Port",199,0,100,"usbhub.jpg","USB 3.0 hub",4.3,"electronic"),
    ("Webcam 1080p HD",850,1350,25,"webcam.jpg","Full HD webcam with mic",4.4,"electronic"),
    ("Portable Charger 10000mAh",699,1100,25,"powerbank.jpg","Dual port power bank",4.5,"electronic"),
    ("Bluetooth Speaker Mini",499,1000,25,"btspeaker.jpg","Portable wireless speaker",4.4,"electronic"),
    ("Screen Cleaning Kit",120,0,100,"screenkit.jpg","Microfiber + spray cleaner",4.2,"electronic"),
    ("Laptop Cooling Pad",350,700,25,"coolingpad.jpg","Dual fan laptop stand",4.3,"electronic"),
    ("HDMI Cable 2m",149,0,100,"hdmicable.jpg","4K HDMI cable",4.4,"electronic"),
    ("Memory Card 32GB",299,0,100,"memorycard.jpg","Class 10 microSD card",4.5,"electronic"),
    ("USB Flash Drive 64GB",399,800,25,"flashdrive.jpg","USB 3.0 flash drive",4.4,"electronic"),
    ("Phone Stand Adjustable",199,0,100,"phonestand.jpg","Adjustable desk phone holder",4.3,"electronic"),
    ("Laptop Stand Aluminium",799,1300,25,"laptopstand.jpg","Ergonomic aluminium stand",4.5,"electronic"),
    ("Wireless Charger Pad",599,1200,25,"wirelesscharger.jpg","10W fast wireless charging",4.4,"electronic"),
    ("LED Strip Lights 5m",349,700,25,"ledstrip.jpg","RGB LED strip with remote",4.3,"electronic"),
    ("Smart Plug WiFi",399,800,25,"smartplug.jpg","Voice control smart plug",4.2,"electronic"),
    ("Keyboard Wrist Rest",199,0,100,"wristrest.jpg","Memory foam wrist support",4.3,"electronic"),
    ("Mouse Pad XL Gaming",299,0,100,"mousepad.jpg","Extended gaming mouse pad",4.4,"electronic"),
    ("Cable Organizer Clips",99,0,100,"cableorganizer.jpg","Desk cable management clips",4.2,"electronic"),
    ("Earphone Case Hard",149,0,100,"earphonecase.jpg","Hard shell earphone case",4.1,"electronic"),
    ("Laptop Bag Sleeve 15in",549,1100,25,"laptopbag.jpg","Waterproof laptop bag",4.4,"electronic"),
    ("Numeric Keypad USB",349,700,25,"numpad.jpg","Portable USB numeric keypad",4.3,"electronic"),
    ("Monitor Light Bar",899,1450,25,"monitorlight.jpg","LED monitor reading light",4.5,"electronic"),
    ("Gamepad Controller USB",699,1100,25,"gamepad.jpg","Wired USB game controller",4.4,"electronic"),
    ("Bluetooth Keyboard Mini",799,1300,25,"btkeyboard.jpg","Compact bluetooth keyboard",4.3,"electronic"),
    ("Digital Alarm Clock",299,0,100,"alarmclock.jpg","LED display alarm clock",4.2,"electronic"),
    ("Extension Board 6 Socket",399,800,25,"extensionboard.jpg","Surge protected extension",4.4,"electronic"),
    ("Cable USB-A to Micro",79,0,100,"microusb.jpg","Micro USB charging cable",4.1,"electronic"),
    ("Phone Camera Lens Kit",499,1000,25,"cameralens.jpg","Clip-on phone camera lens",4.2,"electronic"),
    ("Portable Mini Fan USB",249,0,100,"minifan.jpg","USB powered desk fan",4.0,"electronic"),
    ("Earbuds TWS Wireless",999,1600,25,"tws.jpg","True wireless earbuds",4.5,"electronic"),
    ("Drawing Tablet Small",1499,2400,25,"drawingtablet.jpg","USB drawing pad for design",4.4,"electronic"),
    ("Pocket Projector Mini",4999,7000,25,"projector.jpg","Mini portable projector",4.3,"electronic"),
    ("Smart LED Bulb WiFi",349,700,25,"smartbulb.jpg","Voice control smart bulb",4.2,"electronic"),
    ("Keyboard Backlit USB",549,1100,25,"backlitkeys.jpg","Rainbow backlit keyboard",4.3,"electronic"),
    ("VR Headset Mobile",799,1300,25,"vrheadset.jpg","Mobile VR headset",4.1,"electronic"),
    ("Action Camera Mini",3499,4900,25,"actioncam.jpg","Waterproof action camera",4.4,"electronic"),
    ("Digital Scale 5kg",349,700,25,"digitalscale.jpg","Kitchen digital scale",4.3,"electronic"),
    ("FM Radio Portable",299,0,100,"fmradio.jpg","Portable AM/FM radio",4.0,"electronic"),
    ("Electric Eraser USB",199,0,100,"electriceraser.jpg","Rechargeable electric eraser",4.2,"electronic"),
    ("Webcam Cover Slider",49,0,100,"webcamcover.jpg","Privacy webcam cover",4.1,"electronic"),
    ("Type-C Hub 7in1",899,1450,25,"typechub.jpg","7-in-1 USB-C hub",4.5,"electronic"),
    ("Ring Light 10inch",999,1600,25,"ringlight.jpg","LED ring light with stand",4.4,"electronic"),
    ("Noise Machine Sleep",1299,2100,25,"noisemachine.jpg","White noise sleep machine",4.3,"electronic"),

    # BAGS (50)
    ("Canvas School Bag",350,700,25,"schoolbag.jpg","Durable canvas backpack",4.7,"bag"),
    ("Neoprene Laptop Sleeve",700,1100,25,"laptopsleeve.jpg","Waterproof laptop protection",4.5,"bag"),
    ("Hiking Daypack 25L",400,800,25,"daypack.jpg","Breathable mesh backpack",4.3,"bag"),
    ("Rolling Trolley Bag",1500,2400,25,"trolleybag.jpg","360 spinner wheels luggage",4.4,"bag"),
    ("Gym Duffle Bag",499,1000,25,"dufflebag.jpg","Sports gym bag with pockets",4.3,"bag"),
    ("Tote Bag Canvas Large",299,0,100,"totebag.jpg","Reusable canvas tote",4.4,"bag"),
    ("Waterproof Dry Bag 10L",349,700,25,"drybag.jpg","Roll-top waterproof bag",4.2,"bag"),
    ("Laptop Backpack 30L",899,1450,25,"laptopbackpack.jpg","Anti-theft laptop backpack",4.5,"bag"),
    ("Mini Crossbody Bag",399,800,25,"crossbodybag.jpg","Compact crossbody purse",4.3,"bag"),
    ("Travel Packing Cubes 4pc",499,1000,25,"packingcubes.jpg","Set of 4 packing organizers",4.4,"bag"),
    ("Camera Bag Shoulder",799,1300,25,"camerabag.jpg","Padded camera shoulder bag",4.3,"bag"),
    ("Tactical Backpack 45L",1199,1900,25,"tacticalpack.jpg","Military style tactical bag",4.4,"bag"),
    ("Fanny Pack Waist Bag",249,0,100,"fannypack.jpg","Adjustable waist bag",4.2,"bag"),
    ("College Backpack 20L",599,1200,25,"collegebag.jpg","Stylish college backpack",4.5,"bag"),
    ("Diaper Bag Multifunction",999,1600,25,"diaperbag.jpg","Large capacity baby bag",4.4,"bag"),
    ("Drawstring Bag Sport",149,0,100,"drawstring.jpg","Lightweight gym sack",4.1,"bag"),
    ("Leather Messenger Bag",1299,2100,25,"messengerbag.jpg","PU leather shoulder bag",4.4,"bag"),
    ("Foldable Shopping Bag",99,0,100,"shoppingbag.jpg","Foldable reusable bag",4.2,"bag"),
    ("Hard Shell Suitcase 20in",2499,3500,25,"suitcase.jpg","Spinner hard shell cabin",4.5,"bag"),
    ("Document Holder Bag",299,0,100,"documentbag.jpg","Slim portfolio document bag",4.3,"bag"),
    ("String Backpack Mesh",199,0,100,"meshbag.jpg","Breathable mesh backpack",4.1,"bag"),
    ("Laptop Sleeve 13inch",399,800,25,"sleeve13.jpg","Neoprene 13 inch sleeve",4.3,"bag"),
    ("Backpack Rain Cover",199,0,100,"raincover.jpg","Universal backpack rain cover",4.2,"bag"),
    ("Lunch Bag Insulated",249,0,100,"lunchbag.jpg","Thermal insulated lunch bag",4.4,"bag"),
    ("Shoulder Bag Oxford",349,700,25,"oxfordbag.jpg","Oxford fabric shoulder bag",4.2,"bag"),
    ("Travel Neck Pouch",199,0,100,"neckpouch.jpg","RFID blocking neck pouch",4.3,"bag"),
    ("Kids School Bag",399,800,25,"kidsbag.jpg","Cartoon printed kids bag",4.5,"bag"),
    ("Trekking Bag 60L",1799,2500,25,"trekkingbag.jpg","Frame trekking backpack",4.4,"bag"),
    ("Pouch Set 3pc",199,0,100,"pouchset.jpg","Travel organizer pouch set",4.3,"bag"),
    ("Tool Bag Canvas",449,900,25,"toolbag.jpg","Heavy canvas tool bag",4.2,"bag"),
    ("Sports Backpack 35L",699,1100,25,"sportspack.jpg","Ventilated sport backpack",4.4,"bag"),
    ("Yoga Mat Bag",299,0,100,"yogabag.jpg","Yoga mat carry bag",4.3,"bag"),
    ("Drawstring Bag Printed",179,0,100,"printedstring.jpg","Custom print drawstring",4.1,"bag"),
    ("College Sling Bag",349,700,25,"slingbag.jpg","Single shoulder sling bag",4.3,"bag"),
    ("Expandable Duffel 40L",799,1300,25,"expandable.jpg","Expandable travel duffel",4.4,"bag"),
    ("Anti-Theft Backpack",1099,1750,25,"antitheft.jpg","Hidden zipper backpack",4.5,"bag"),
    ("Leather Wallet Bag",599,1200,25,"walletbag.jpg","Chain wallet crossbody",4.2,"bag"),
    ("Book Bag with Handle",249,0,100,"bookbag.jpg","Top handle book bag",4.1,"bag"),
    ("Weekender Bag Duffel",899,1450,25,"weekender.jpg","Overnight weekender bag",4.3,"bag"),
    ("Transparent PVC Bag",299,0,100,"pvcbag.jpg","Clear PVC tote bag",4.0,"bag"),
    ("Backpack Chest Strap",699,1100,25,"cheststrap.jpg","Ergonomic chest strap bag",4.3,"bag"),
    ("Mini Backpack Cute",449,900,25,"minibackpack.jpg","Trendy mini backpack",4.4,"bag"),
    ("Eco Jute Bag",149,0,100,"jutebag.jpg","Natural jute tote",4.2,"bag"),
    ("Garment Bag Travel",499,1000,25,"garmentbag.jpg","Suit travel garment bag",4.3,"bag"),
    ("Briefcase Laptop Bag",1499,2400,25,"briefcase.jpg","Professional briefcase",4.5,"bag"),
    ("Compression Packing Bag",299,0,100,"compressionbag.jpg","Space saving packing bag",4.3,"bag"),
    ("Bottle Holder Bag",149,0,100,"bottleholder.jpg","Insulated bottle carrier",4.1,"bag"),
    ("Shoe Bag Travel",199,0,100,"shoebag.jpg","Drawstring shoe travel bag",4.2,"bag"),
    ("Pencil Case Large",149,0,100,"pencilcase.jpg","Zippered pencil case",4.3,"bag"),
    ("Pouch Waterproof Phone",99,0,100,"phonepouch.jpg","Waterproof phone pouch",4.2,"bag"),

    # ACCESSORIES (50)
    ("Stainless Steel Water Bottle",50,0,100,"waterbottle.jpg","500ml insulated bottle",4.3,"accessory"),
    ("Steel Lunch Box Compartment",80,0,100,"lunchbox.jpg","3-compartment steel lunch box",4.4,"accessory"),
    ("Polarized UV Sunglasses",350,700,25,"sunglasses.jpg","Driving polarized lens",4.2,"accessory"),
    ("Genuine Leather Wallet",250,0,100,"leatherwallet.jpg","Bifold card wallet",4.3,"accessory"),
    ("Canvas Web Belt",150,0,100,"belt.jpg","Adjustable fabric belt",4.1,"accessory"),
    ("Quartz Wrist Watch",1200,1900,25,"quarzwatch.jpg","Steel case with leather strap",4.5,"accessory"),
    ("Copper Water Bottle",299,0,100,"copperbottle.jpg","Pure copper water bottle",4.4,"accessory"),
    ("Titanium Metal Watch",1899,2700,25,"metalwatch.jpg","Titanium case sport watch",4.5,"accessory"),
    ("Polarized Sports Goggles",499,1000,25,"goggles.jpg","Anti-fog sports goggles",4.3,"accessory"),
    ("Card Holder Slim",199,0,100,"cardholder.jpg","Minimalist card holder",4.4,"accessory"),
    ("Travel Pillow Neck",349,700,25,"travelpillow.jpg","Memory foam neck pillow",4.3,"accessory"),
    ("Umbrella Auto Open",299,0,100,"umbrella.jpg","Windproof auto umbrella",4.4,"accessory"),
    ("Leather Keyholder",149,0,100,"keyholder.jpg","Genuine leather key ring",4.2,"accessory"),
    ("Insulated Flask 750ml",449,900,25,"flask.jpg","Double wall steel flask",4.5,"accessory"),
    ("Sports Wristband 2pc",99,0,100,"wristband.jpg","Sweat absorbing wristbands",4.1,"accessory"),
    ("Pocket Knife Swiss",599,1200,25,"pocketknife.jpg","Multi-tool pocket knife",4.4,"accessory"),
    ("Silicone Watch Band",199,0,100,"watchband.jpg","Replacement silicone strap",4.3,"accessory"),
    ("Carabiner Clip 4pc",149,0,100,"carabiner.jpg","Aluminium carabiner clips",4.2,"accessory"),
    ("Bamboo Sunglasses",349,700,25,"bamboogoggles.jpg","Eco bamboo frame glasses",4.3,"accessory"),
    ("Coin Purse Leather",149,0,100,"coinpurse.jpg","Small zip coin purse",4.1,"accessory"),
    ("Phone Pop Socket",99,0,100,"popsocket.jpg","Grip and stand pop socket",4.3,"accessory"),
    ("Magnetic Phone Mount",199,0,100,"phonemount.jpg","Dashboard magnetic mount",4.2,"accessory"),
    ("Luggage Tag Leather",99,0,100,"luggagetag.jpg","Personalized luggage tag",4.1,"accessory"),
    ("Passport Holder",199,0,100,"passportholder.jpg","RFID blocking passport cover",4.4,"accessory"),
    ("Sunscreen Stick SPF50",149,0,100,"sunscreen.jpg","Portable SPF50 sunscreen",4.2,"accessory"),
    ("Watch Winder Single",599,1200,25,"watchwinder.jpg","Automatic watch winder box",4.3,"accessory"),
    ("Tie Clip Silver",199,0,100,"tieclip.jpg","Stainless steel tie bar",4.2,"accessory"),
    ("Cufflinks Formal",249,0,100,"cufflinks.jpg","Silver plated cufflinks",4.3,"accessory"),
    ("Hair Tie Set 20pc",99,0,100,"hairtie.jpg","Elastic hair tie set",4.2,"accessory"),
    ("Scrunchie Set 5pc",149,0,100,"scrunchie.jpg","Velvet scrunchie set",4.3,"accessory"),
    ("Headband Sports",99,0,100,"headband.jpg","Non-slip sport headband",4.1,"accessory"),
    ("Cooling Towel Sport",199,0,100,"coolingtowel.jpg","Instant cooling sport towel",4.3,"accessory"),
    ("Bottle Opener Keychain",79,0,100,"bottleopener.jpg","Metal bottle opener ring",4.0,"accessory"),
    ("Pen Knife Multi Tool",399,800,25,"multitool.jpg","12-in-1 multi tool",4.4,"accessory"),
    ("Slim Bifold Wallet",299,0,100,"sliswallet.jpg","Ultra slim bifold",4.3,"accessory"),
    ("Compression Socks 3pc",199,0,100,"compressionocks.jpg","Travel compression socks",4.2,"accessory"),
    ("Cap Baseball Cotton",249,0,100,"cap.jpg","Adjustable cotton cap",4.3,"accessory"),
    ("Beanie Woolen Cap",199,0,100,"beanie.jpg","Soft knit winter beanie",4.2,"accessory"),
    ("Scarf Soft Cotton",149,0,100,"scarf.jpg","Lightweight cotton scarf",4.1,"accessory"),
    ("Gloves Touch Screen",199,0,100,"gloves.jpg","Winter touchscreen gloves",4.3,"accessory"),
    ("Sunglasses Case Hard",149,0,100,"sunglasscase.jpg","Hard clamshell glasses case",4.2,"accessory"),
    ("Pen Organizer Leather",249,0,100,"penorganizer.jpg","Leather pen roll organizer",4.3,"accessory"),
    ("Phone Lanyard Neck",99,0,100,"phonelandyard.jpg","Adjustable phone lanyard",4.1,"accessory"),
    ("Wax Shoe Polish Kit",149,0,100,"shoepolish.jpg","Complete shoe care kit",4.2,"accessory"),
    ("Shoe Horn Long",99,0,100,"shoehorn.jpg","Long handled shoe horn",4.0,"accessory"),
    ("Travel Adapter Universal",399,800,25,"traveladapter.jpg","Universal plug adapter",4.4,"accessory"),
    ("Silicone Cable Tie 10pc",79,0,100,"cabletie.jpg","Reusable cable organizers",4.1,"accessory"),
    ("Microfiber Cloth 5pc",99,0,100,"microfiber.jpg","Screen cleaning cloths",4.3,"accessory"),
    ("Lens Cleaning Pen",79,0,100,"lenscleaner.jpg","Camera lens cleaning pen",4.2,"accessory"),
    ("Collapsible Water Cup",149,0,100,"collapsiblecup.jpg","Foldable silicone cup",4.1,"accessory"),

    # FOOTWEAR (50)
    ("Running Sports Shoes",1800,2500,25,"runningshoes.jpg","Mesh athletic footwear",4.6,"footwear"),
    ("Foam Flip Flops",300,600,25,"flipflops.jpg","Comfortable casual slippers",4.2,"footwear"),
    ("Leather Casual Shoes",500,1000,25,"casualshoes.jpg","Brown leather loafers",4.3,"footwear"),
    ("Canvas Sneakers White",599,1200,25,"whitesneakers.jpg","Classic white canvas shoes",4.4,"footwear"),
    ("Trekking Sandals",799,1300,25,"trekkingsandals.jpg","Outdoor adventure sandals",4.3,"footwear"),
    ("High Top Sneakers",899,1450,25,"hightop.jpg","High top canvas sneakers",4.4,"footwear"),
    ("Formal Oxford Shoes",1299,2100,25,"oxfordshoes.jpg","Classic leather Oxfords",4.5,"footwear"),
    ("Rain Boots Waterproof",999,1600,25,"rainboots.jpg","PVC waterproof rain boots",4.3,"footwear"),
    ("Slippers Memory Foam",349,700,25,"memoryfoam.jpg","Memory foam indoor slippers",4.5,"footwear"),
    ("Sports Sandals",499,1000,25,"sportsandals.jpg","Adjustable sport sandals",4.3,"footwear"),
    ("Ankle Boots Chelsea",1499,2400,25,"chelseaboots.jpg","Elastic sided ankle boots",4.4,"footwear"),
    ("Ballet Flats Women",699,1100,25,"balletflats.jpg","Soft ballet flat shoes",4.3,"footwear"),
    ("Loafers Slip-on Men",899,1450,25,"loafers.jpg","Comfortable slip-on loafers",4.4,"footwear"),
    ("Platform Sneakers",999,1600,25,"platformsneakers.jpg","Chunky platform shoes",4.3,"footwear"),
    ("Moccasins Suede",799,1300,25,"moccasins.jpg","Soft suede moccasins",4.4,"footwear"),
    ("Sandals Flat Casual",399,800,25,"flatsandals.jpg","Everyday casual sandals",4.2,"footwear"),
    ("Trail Running Shoes",1599,2200,25,"trailshoes.jpg","Off-road trail runners",4.5,"footwear"),
    ("Espadrilles Canvas",499,1000,25,"espadrilles.jpg","Summer espadrille shoes",4.2,"footwear"),
    ("Work Boots Steel Toe",1899,2700,25,"workboots.jpg","Safety steel toe boots",4.4,"footwear"),
    ("Gym Training Shoes",1199,1900,25,"gymshoes.jpg","Cross training gym shoes",4.4,"footwear"),
    ("Wedge Heels Women",899,1450,25,"wedgeheels.jpg","Comfortable wedge shoes",4.3,"footwear"),
    ("Clogs Wooden Sole",599,1200,25,"clogs.jpg","Comfortable wooden clogs",4.1,"footwear"),
    ("Boat Shoes Deck",799,1300,25,"boatshoes.jpg","Non-slip deck shoes",4.3,"footwear"),
    ("Sandals Kolhapuri",349,700,25,"kolhapuri.jpg","Traditional kolhapuri chappals",4.4,"footwear"),
    ("Slip Resistant Kitchen",499,1000,25,"kitchenshoes.jpg","Non-slip work shoes",4.3,"footwear"),
    ("Hiking Boots Mid",1699,2400,25,"hikingboots.jpg","Waterproof mid hiking boots",4.5,"footwear"),
    ("Dress Sandals Heeled",799,1300,25,"dresssandals.jpg","Party heeled sandals",4.3,"footwear"),
    ("Kids Sports Shoes",699,1100,25,"kidsshoes.jpg","Lightweight kids trainers",4.5,"footwear"),
    ("Breathable Mesh Shoes",799,1300,25,"meshshoes.jpg","Ultra breathable mesh",4.4,"footwear"),
    ("Slip-on Vans Style",699,1100,25,"vansstyle.jpg","Classic slip-on sneakers",4.3,"footwear"),
    ("Formal Derby Shoes",1199,1900,25,"derbyshoes.jpg","Lace-up formal derbies",4.4,"footwear"),
    ("Open Toe Heels",799,1300,25,"opentoeheels.jpg","Strappy open toe heels",4.2,"footwear"),
    ("Snow Boots Warm",1299,2100,25,"snowboots.jpg","Insulated snow boots",4.4,"footwear"),
    ("Casual Chukka Boots",1099,1750,25,"chukkaboots.jpg","Suede chukka ankle boots",4.3,"footwear"),
    ("Pool Slides Comfort",249,0,100,"poolslides.jpg","Cushioned pool slides",4.2,"footwear"),
    ("Woven Flat Sandals",449,900,25,"wovensandals.jpg","Handwoven flat sandals",4.3,"footwear"),
    ("Sneakers Chunky Sole",1099,1750,25,"chunkysole.jpg","Retro chunky sole shoes",4.4,"footwear"),
    ("Driving Moccasins",999,1600,25,"drivingmoc.jpg","Soft leather driving shoes",4.3,"footwear"),
    ("Toe Ring Sandals",299,0,100,"toering.jpg","Traditional toe ring sandal",4.1,"footwear"),
    ("Faux Leather Boots",899,1450,25,"fauxboots.jpg","Vegan leather ankle boots",4.3,"footwear"),
    ("Jelly Sandals Kids",199,0,100,"jellysandals.jpg","PVC jelly sandals kids",4.2,"footwear"),
    ("Athleisure Shoes",999,1600,25,"athleisure.jpg","Casual athleisure sneakers",4.4,"footwear"),
    ("Platform Sandals",699,1100,25,"platformsandals.jpg","Thick sole platform sandals",4.3,"footwear"),
    ("Lace-up Canvas Shoes",499,1000,25,"laceupcavas.jpg","Classic canvas lace-up",4.2,"footwear"),
    ("Gum Sole Sneakers",799,1300,25,"gumsole.jpg","Retro gum sole trainers",4.3,"footwear"),
    ("Rubber Rain Sandals",299,0,100,"rubbersandals.jpg","Waterproof rubber sandals",4.1,"footwear"),
    ("Toe Post Flip Flops",199,0,100,"toepost.jpg","Classic toe post slippers",4.2,"footwear"),
    ("Walking Shoes Wide",899,1450,25,"wideshoes.jpg","Wide fit comfort walkers",4.4,"footwear"),
    ("Ankle Strap Heels",899,1450,25,"anklestrap.jpg","Block heel ankle strap",4.3,"footwear"),
    ("Barefoot Minimalist",1199,1900,25,"barefoot.jpg","Zero drop minimalist shoes",4.4,"footwear")
]

cur.execute("DELETE FROM products")
cur.executemany(
    "INSERT INTO products(name,price,original_price,stock,image,description,rating,category) VALUES(?,?,?,?,?,?,?,?)",
    products
)

conn.commit()
conn.close()
print(f"✅ Database ready with {len(products)} products + orders table!")